services:
  - type: web
    name: hiring-form
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hiring-db
          property: connectionString

databases:
  - name: hiring-db
    plan: free
